name: dewey-rag-server
channels:
  - conda-forge
  - pytorch
  - nvidia
  - huggingface
dependencies:
  - python=3.11
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - torchaudio>=2.1.0
  - cudatoolkit=12.1
  - pip
  - git
  - git-lfs
  - pip:
    - transformers>=4.36.0
    - accelerate>=0.25.0
    - bitsandbytes>=0.41.0
    - peft>=0.7.0
    - trl>=0.7.0
    - datasets>=2.15.0
    - numpy>=1.24.0
    - pandas>=2.0.0
    - scipy>=1.11.0
    - PyPDF2>=3.0.0
    - pdfplumber>=0.9.0
    - pymupdf>=1.23.0
    - faiss-gpu>=1.7.4
    - chromadb>=0.4.0
    - sentence-transformers>=2.2.2
    - tiktoken>=0.5.0
    - spacy>=3.7.0
    - nltk>=3.8.0
    - tqdm>=4.65.0
    - wandb>=0.16.0
    - tensorboard>=2.15.0
    - psutil>=5.9.0
    - fastapi>=0.104.0
    - uvicorn>=0.24.0
    - gradio>=4.0.0
    - streamlit>=1.28.0
    - scikit-learn>=1.3.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - plotly>=5.17.0
    - memory-profiler>=0.61.0
    - optimum>=1.14.0
    - jupyter>=1.0.0
    - ipywidgets>=8.1.0
    - streamlit>=1.28.0
    - plotly>=5.17.0
    - altair>=5.0.0
    - huggingface-hub>=0.19.0
    - safetensors>=0.4.0